"""initial schema

Revision ID: 07ead28ac650
Revises: 
Create Date: 2026-08-13 10:14:56.403881
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.base import GUID


revision: str = '07ead28ac650'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_careers'))
    )
    op.create_index(op.f('ix_careers_code'), 'careers', ['code'], unique=True)
    op.create_table('classrooms',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classrooms'))
    )
    op.create_index(op.f('ix_classrooms_code'), 'classrooms', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('user_id', GUID(length=32), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.create_table('students',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('user_id', GUID(length=32), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('career_id', GUID(length=32), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('fk_students_career_id_careers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('user_id', name=op.f('uq_students_user_id'))
    )
    op.create_index(op.f('ix_students_registration_number'), 'students', ['registration_number'], unique=True)
    op.create_table('subjects',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('career_id', GUID(length=32), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('fk_subjects_career_id_careers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_table('teachers',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('user_id', GUID(length=32), nullable=False),
    sa.Column('employee_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teachers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_teachers_user_id'))
    )
    op.create_index(op.f('ix_teachers_employee_number'), 'teachers', ['employee_number'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', GUID(length=32), nullable=False),
    sa.Column('role_id', GUID(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id_role_id'))
    )
    op.create_table('commissions',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('subject_id', GUID(length=32), nullable=False),
    sa.Column('career_id', GUID(length=32), nullable=False),
    sa.Column('teacher_id', GUID(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('fk_commissions_career_id_careers')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_commissions_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_commissions_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commissions'))
    )
    op.create_index(op.f('ix_commissions_code'), 'commissions', ['code'], unique=True)
    op.create_table('enrollments',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('student_id', GUID(length=32), nullable=False),
    sa.Column('commission_id', GUID(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], name=op.f('fk_enrollments_commission_id_commissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_enrollments_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('student_id', 'commission_id', name=op.f('uq_enrollments_student_id_commission_id'))
    )
    op.create_index(op.f('ix_enrollments_commission_id'), 'enrollments', ['commission_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('commission_id', GUID(length=32), nullable=False),
    sa.Column('classroom_id', GUID(length=32), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_schedules_classroom_id_classrooms')),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], name=op.f('fk_schedules_commission_id_commissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index(op.f('ix_schedules_commission_id'), 'schedules', ['commission_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('commission_id', GUID(length=32), nullable=False),
    sa.Column('schedule_id', GUID(length=32), nullable=True),
    sa.Column('classroom_id', GUID(length=32), nullable=True),
    sa.Column('teacher_id', GUID(length=32), nullable=True),
    sa.Column('created_by', GUID(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('late_grace_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_classes_classroom_id_classrooms')),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], name=op.f('fk_classes_commission_id_commissions')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_classes_created_by_users')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_classes_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_classes_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    comment='Instancia de clase (sesión)'
    )
    op.create_index(op.f('ix_classes_commission_id'), 'classes', ['commission_id'], unique=False)
    op.create_index(op.f('ix_classes_date'), 'classes', ['date'], unique=False)
    op.create_index(op.f('ix_classes_status'), 'classes', ['status'], unique=False)
    op.create_table('attendance',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('class_id', GUID(length=32), nullable=False),
    sa.Column('student_id', GUID(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_attendance_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('class_id', 'student_id', name=op.f('uq_attendance_class_id_student_id'))
    )
    op.create_index(op.f('ix_attendance_class_id'), 'attendance', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('qr_sessions',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('class_id', GUID(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', GUID(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_qr_sessions_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_qr_sessions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_qr_sessions_token_hash'))
    )
    op.create_index(op.f('ix_qr_sessions_class_id'), 'qr_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_qr_sessions_expires_at'), 'qr_sessions', ['expires_at'], unique=False)
    op.create_table('attendance_events',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('attendance_id', GUID(length=32), nullable=False),
    sa.Column('class_id', GUID(length=32), nullable=True),
    sa.Column('student_id', GUID(length=32), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_by', GUID(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], name=op.f('fk_attendance_events_attendance_id_attendance'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_attendance_events_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_attendance_events_created_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_events_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_events'))
    )
    op.create_index(op.f('ix_attendance_events_attendance_id'), 'attendance_events', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_class_id'), 'attendance_events', ['class_id'], unique=False)
    op.create_table('justifications',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('attendance_id', GUID(length=32), nullable=False),
    sa.Column('student_id', GUID(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', GUID(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], name=op.f('fk_justifications_attendance_id_attendance'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_justifications_reviewed_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_justifications_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_justifications'))
    )
    op.create_index(op.f('ix_justifications_attendance_id'), 'justifications', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_justifications_student_id'), 'justifications', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_justifications_student_id'), table_name='justifications')
    op.drop_index(op.f('ix_justifications_attendance_id'), table_name='justifications')
    op.drop_table('justifications')
    op.drop_index(op.f('ix_attendance_events_class_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_attendance_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_qr_sessions_expires_at'), table_name='qr_sessions')
    op.drop_index(op.f('ix_qr_sessions_class_id'), table_name='qr_sessions')
    op.drop_table('qr_sessions')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_class_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_classes_status'), table_name='classes')
    op.drop_index(op.f('ix_classes_date'), table_name='classes')
    op.drop_index(op.f('ix_classes_commission_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_schedules_commission_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_commission_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_commissions_code'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_teachers_employee_number'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_students_registration_number'), table_name='students')
    op.drop_table('students')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_classrooms_code'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_careers_code'), table_name='careers')
    op.drop_table('careers')
    # ### end Alembic commands ###
